abstract: File based storage model for Catalyst.
author: Ash Berlin, C<ash@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Model-File
no_index: 
  directory: 
    - t/lib
    - inc
    - t
requires: 
  Catalyst: 5.69
  Path::Class: 0.15
  perl: 5.8.1
version: 0.05
